### ISSUE TITLE
Set up pull-request template

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#1]
Github allows to [set up pull request templates](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/). This can be useful to provide checklists of things that pull request submitters should do or requirements they should meet that we can't check or provide feedback on fully automatically. This is probably also already useful as we are merging in things ourselves.

These checklists integrate with the workflow of Github and are specified for example on the PR overview lists.

As an example, we could specify a checklist such as:

## Packaging requirements
* [ ] Provides LICENSE file
* [ ] `META` file specifies
  * [ ] X
  * [ ] Y
  * [ ] Z

**Comment by dstebila** [comment]
Also need a CONTRIBUTING.md file along side the pull request template

**Comment by dstebila** [comment]
Resolved by 764935084a48dc5ffb03f7dd7e6c48ef595411ae
