### ISSUE TITLE
Run tests from a more sophisticated script

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#10]
The `Makefile` is getting unwieldy, and it turns out that some tests can't be run on all platforms.

For example, Valgrind is broken on MacOS. This makes the build even more annoying, as the `run-valgrind` target is now conditional.

We'd also like to produce all errors in one go; not abort after the first make target failed.

It's probably better then to write a Python or more advanced shell script to make these decisions and filter for us. It would probably also help reduce the output from Make (which produces a LOT of noise).

**Comment by dstebila** [comment]
I think it's a good idea to move most of the checks out of the top-level Makefile and into bash or Python scripts.

Whatever we do here, we want to have sufficiently relevant messages logged to stdout, because this is all that you can see when a Travis build fails.

**Comment by dstebila** [comment]
Looking at it more closely, I see you've started that with `check_*.py` scripts in the `test` directory, some of which have the semantics that you provide a scheme name `crypto_kem/kyber768` as the input.  But there are still Makefile targets for `run-testvectors-all`, etc.  

Could we have a single Makefile target `run-checks` which then basically does: 

    for all scripts in test/check*.py
        for all schemes in (crypto_kem/*, crypto_sig/*):
            $script $scheme

We could even wrap this in its own script which nicely catches errors and organizes log output.

Benefits: the Makefile stays short.  

Drawbacks: harder for a developer to run all of a certain type of test (e.g., just run-testvectors-all).

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> I think it's a good idea to move most of the checks out of the
> top-level Makefile and into bash or Python scripts.
> 
> Whatever we do here, we want to have sufficiently relevant messages
> logged to stdout, because this is all that you can see when a Travis
> build fails.

I fully agree. Let's aim for one script per test.

**Comment by dstebila** [comment]
I have some time today and could work on this, unless someone's already got some work in progress here.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> I have some time today and could work on this, unless someone's
> already got some work in progress here.

I think I'm still entertained with setting up my server again and then
installing Windows in a VM.

**Comment by thomwiggers** [comment]
I talked about this a little bit with Joost already and we at least identified the following points:

* It's probably helpful to have some shared python module to do some common things:
  * get a list of schemes
  * load a meta file for a scheme
  * Maybe other things, such as some common handling of arguments to e.g. set up logging

* It's probably helpful to use Python's `logging` functionality, to allow to easily set verbosity and on CI only print out things when things break.
  * There is a helpful python module called `colorlog` to get prettier output https://github.com/borntyping/python-colorlog

* We want the implementation to be python 3.

**Comment by dstebila** [comment]
See PR #25.  It doesn't yet do all the tests that are in the top-level `Makefile`.  If you like this approach, then we would eventually move all of those over to this approach.

**Comment by dstebila** [comment]
See alternative approach in PR #27.

**Comment by dstebila** [comment]
Things left to transition over:

- [X] check symbol namespace - see PR #30 
- [ ] check metadata
- [ ] check test vectors
- [ ] valgrind on functional tests
- [ ] sanitizer on functional tests
- [ ] check format

**Comment by dstebila** [comment]
I've done all I can do here.  I'm not sure how you want to move valgrind and sanitizer, as well as the various format/tidy checks, into the pythonic framework.
