### ISSUE TITLE
kyber768 API always returns zero

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#11]
The Kyber768 `crypto_kem_dec` function always returns zero, even though decapsulation fails.

See tests added in 31449679bd2cb7942b4f1c4f94a47da5b6a0d024 and the result https://travis-ci.com/PQClean/PQClean/jobs/172380776

**Comment by joostrijneveld** [comment]
Yes, this is a result of the CCA transform; decapsulation failure results in a uniformly random key, but it's unclear what 'failing' means in the context of a C function here. I cannot immediately think of a scenario or example in which any decapsulation should return `-1`. We should discuss what we actually want to check w.r.t. that return code requirement.

**Comment by thomwiggers** [comment]
Yeah, @joostrijneveld also pointed that out – but then it is slightly unclear what 'failure' means and we should probably clarify that in the API description.
