### ISSUE TITLE
Should we also check against NIST submission KAT values?

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#110]
Because we are using our own format for test vectors, and thereafter a hash of those, our testvector checks end up ensuring consistency of our implementations with themselves over time.  But we don't have any check against the "canonical" implementation fro the NIST submissions, so it could be that our first version (which we used to generate the hash of the test vectors) is already distinct/incompatible/wrong.  We should have some check against the "ground truth" established by the code in the NIST submissions.

**Comment by joostrijneveld** [comment]
I think that's very useful. I see that you replaced the AES implementation that they depended on OpenSSL for with a call to our own; with this dependency resolved, I don't really see any reason for doing our own test vector generation anymore.

**Comment by dstebila** [comment]
More rounds is probably good to have, but I also like CI tests that finish quickly. :)  Yes I suppose we could have multiple hashes.  On the one hand yes we could get rid of our own test vector generation, but I wasn't necessarily implying this, I just wanted to check that I hadn't screwed up any implementations I'd ported over.

**Comment by dstebila** [comment]
Fixed by #111
