### ISSUE TITLE
Why does the detached signature API return the signature length

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#113]
The detached signature API is specified as follows:

```c
int PQCLEAN_YOURSCHEME_CLEAN_crypto_sign_signature(
    uint8_t *sig, size_t *siglen,
    const uint8_t *m, size_t mlen,
    const uint8_t *sk);
int PQCLEAN_YOURSCHEME_CLEAN_crypto_sign_verify(
    const uint8_t *sig, size_t siglen,
    const uint8_t *m, size_t mlen,
    const uint8_t *pk);
```

Is CRYPTO_BYTES a maximum length on the signature, or was it not necessary to return this length in the first place?

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> The detached signature API is specified as follows:
> 
> ```c
> int PQCLEAN_YOURSCHEME_CLEAN_crypto_sign_signature(
>     uint8_t *sig, size_t *siglen,
>     const uint8_t *m, size_t mlen,
>     const uint8_t *sk);
> int PQCLEAN_YOURSCHEME_CLEAN_crypto_sign_verify(
>     const uint8_t *sig, size_t siglen,
>     const uint8_t *m, size_t mlen,
>     const uint8_t *pk);
> ```
> 
> Is CRYPTO_BYTES a maximum length on the signature, or is was it not
> necessary to return this length in the first place?

Indeed, CRYPTO_BYTES is the maximum length.
