### ISSUE TITLE
Add Round 2 KEM RQC

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#126]

**Comment by dstebila** [comment]
I've emailed the RQC team and they're interested, they'll follow up with us next week, and then I'll have a clearer idea of how this one will proceed.

**Comment by mkannwischer** [comment]
The RQC team announced at the 2nd NIST PQC workshop that they are working on integration into PQClean.

**Comment by dstebila** [comment]
Closing issue since RQC not in round 3.
