### ISSUE TITLE
Add Round 2 KEM Kyber

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#129]

**Comment by thomwiggers** [comment]
I think @cryptojedi has some work in branch [kyberv2](https://github.com/PQClean/PQClean/tree/kyberv2)

**Comment by mkannwischer** [comment]
Can we close this issue? Or do we still want to add the "90s" variant of Kyber?

**Comment by cryptojedi** [comment]
"Matthias J. Kannwischer" <notifications@github.com> wrote:
> Can we close this issue? Or do we still want to add the "90s" variant of Kyber?

I would for the moment leave it at the non-90s version; maybe add 90s
version once we add optimized code.

**Comment by dstebila** [comment]
> > Can we close this issue? Or do we still want to add the "90s" variant of Kyber?

> I would for the moment leave it at the non-90s version; maybe add 90s version once we add optimized code.

I've added issue #173 to track adding the 90s versions.
