### ISSUE TITLE
Add Round 2 signature scheme Dilithium

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#136]

**Comment by dstebila** [comment]
Hi Panos, it is definitely our plan to get all of the Round 2 algorithms including Falcon and Dilithium into PQClean over the next couple of months, and use the PQClean implementation to add them to liboqs.  As far as I know we haven't assigned Falcon or Dilithium to any one of our developers yet, so if you wanted to have a go at adding one or both of them to PQClean, you'd be welcome to do so, just post a comment here so we know someone's working on it.

**Comment by csosto-pk** [comment]
Will do. My student will start in June, so we will update these two issues accordingly, unless @cryptojedi completes the work in the meanwhile.

**Comment by mkannwischer** [comment]
I can take care of Dilithium now. Should be done by the end of the week.

**Comment by csosto-pk** [comment]
> I can take care of Dilithium now. Should be done by the end of the week.

Thank you Matthias, I will keep an eye for it.
