### ISSUE TITLE
Add Round 2 signature scheme Falcon

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#137]

**Comment by csosto-pk** [comment]
Hello Prof Stebila, 
We are about to start some work to bring Dillithium and Falcon to liboqs/openssl this summer to do some testing. Do you happen to know if Falcon will make it to PQClean soon so we avoid duplicating work? 
Thanks

**Comment by dstebila** [comment]
Hi Panos, it is definitely our plan to get all of the Round 2 algorithms including Falcon and Dilithium into PQClean over the next couple of months, and use the PQClean implementation to add them to liboqs.  As far as I know we haven't assigned Falcon or Dilithium to any one of our developers yet, so if you wanted to have a go at adding one or both of them to PQClean, you'd be welcome to do so, just post a comment here so we know someone's working on it.

**Comment by csosto-pk** [comment]
My student will start in June, so we will update this Issue accordingly.

**Comment by mkannwischer** [comment]
I've heard some rumours that the Falcon team might be working on a PQClean integration in the future. Might make sense to coordinate with them to avoid work duplication.

**Comment by csosto-pk** [comment]
> I've heard some rumours that the Falcon team might be working on a PQClean integration in the future. Might make sense to coordinate with them to avoid work duplication.

Thanks Matthias, we appreciate it. I didn't know. We were focusing on integrating Dillithium to liboqs and then to openssl first. 

Falcon was next, so that is good to know.  I will ask the Falcon team.

**Comment by pornin** [comment]
I have begun adding Falcon, see PR #210. I am currently navigating the intricacies of MSVC (e.g. it does not support the C99 keyword "restrict").

**Comment by mkannwischer** [comment]
Thanks @pornin
