### ISSUE TITLE
Document test filtering

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#149]
We have a bunch of filters and we should probably explain how they work.

* `PQCLEAN_ONLY_TYPES`
* `PQCLEAN_SKIP_TYPES`
* `PQCLEAN_ONLY_SCHEMES`
* `PQCLEAN_SKIP_SCHEMES`
* `PQCLEAN_ONLY_DIFF`

**Comment by dstebila** [comment]
Added https://github.com/PQClean/PQClean/wiki/Test-framework to explain test framework.
