### ISSUE TITLE
When running nosetests3 on Debian, test_functest_sanitizers sometimes seems to get stuck. Cancelling and restarting the test run typically solves this,  but we may want to figure out what the reason is

### ISSUE THREAD

**Issue by cryptojedi** [PQClean/PQClean#153]

**Comment by thomwiggers** [comment]
Is this "on Debian" or "in a paravirtualized virtual machine". We have seen similar issues only in containers.

**Comment by cryptojedi** [comment]
It was in Qubes, so virtualized. Still, why would virtualization have any influence on sanitizers?

**Comment by thomwiggers** [comment]
Because the sanitizers hook into some system calls in similar ways, apparently.

**Comment by thomwiggers** [comment]
To be clear, it seems so far that HVM is fine, but other types of virtualization may have issues.

**Comment by thomwiggers** [comment]
We've switched to `pytest`, so maybe this doesn't happen anymore.
