### ISSUE TITLE
Unify Makefiles to reduce compiler flag duplication

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#157]
In #156, it annoyed me a bit that I had to edit the compiler flags in every Makefile. This also makes it quite likely for these compiler flags to get out of sync when we have more than a handful of schemes.

Can we unify these somehow while still maintaining the 'you can build it as a standalone directory' idea?

I realize we've been over this a few times, and don't intend to re-hash the discussion of whether we need a Makefile, but I feel like the current situation is not optimal.

**Comment by cryptojedi** [comment]
Joost Rijneveld <notifications@github.com> wrote:
> In #156, it annoyed me a bit that I had to edit the compiler flags in
> every Makefile. This also makes it quite likely for these compiler
> flags to get out of sync when we have more than a handful of schemes.
> 
> Can we unify these somehow while still maintaining the 'you can build
> it as a standalone directory' idea?

In the long run we'll probably want to have different flags for
different implementations, at least when starting to support optimized
implementations which may need architecture-specific flags.

How about adding a CI test checking that certain flags (e.g., "-Wall
-Wextra -Wmissing-prototypes) are present?

**Comment by thomwiggers** [comment]
> Can we unify these somehow while still maintaining the 'you can build it as a standalone directory' idea?

I don't think we can really do both, while also just using Makefiles – we would really need something like CMakeLists.txt that supports a more recursive structure (in my understanding) with passing parameters somehow if we want to support both local customisation (needed for AVX2, etc), and stuff from elsewhere.
