### ISSUE TITLE
Remove testvectors

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#159]
Since we have NIST KAT checks, we can remove our custom testvector check, I think. Any objections?

**Comment by joostrijneveld** [comment]
Briefly came up in #110; I have no objections.

**Comment by joostrijneveld** [comment]
For signatures, the NIST KAT does not have a way of checking the detached signature API.

**Comment by dstebila** [comment]
Good point... should I remove it just for KEMs?

**Comment by joostrijneveld** [comment]
Yeah, I think that's the best situation we could hope for.

**Comment by dstebila** [comment]
Fixed by #161.
