### ISSUE TITLE
Somehow catch redundant declarations

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#166]
The current SPHINCS code has an issue where the precomputation state array for SHA256 is defined in both `sha256.h` and `sha256.c`. This was caught when trying to link everything together in pqm4, but is not a problem when putting together the `.a` file in pqclean. The difference may be in the fact that pqm4 exposes all .h files through `-I`, but in pqclean it somehow disappears in the indirection created by the `.a`.

I'm not sure if this is a problem we should solve by adding the `-Wredundant-decls` flag to the building of the `.a`, or by changing the build process somewhat (i.e. by linking in the header files).

EDIT: See #167

**Comment by thomwiggers** [comment]
Sounds reasonable to add this.
