### ISSUE TITLE
Incremental hash API constants 

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#171]
The incremental hashing APIs provided by the `common/` directory appear to be doing some assumptions. For example, the incremental hashing API for SHA256 assumes a state of 40 bytes.

Aside from this not being documented, this also leads to some difficulties if anyone wants to substitute the SHA256 implementation. I am trying to replace SHA2 by the Rust Sha2 crate, but because this implementation has a slightly different structure the state is some bytes larger.

I'd propose introducing some constants like `PQCLEAN_SHA2_INCREMENTAL_STATE_BYTES` to then replace the hardcoded constants.

Alternatively, we could also do it with structs, like the AES api.

**Comment by thomwiggers** [comment]
Having spent a few more minutes thinking about this, I think I'd prefer a struct for the state, as this would allow the type checker to verify that things are being used correctly.

**Comment by joostrijneveld** [comment]
We talked about this offline for a bit; I agree - a struct seems to be the right approach here (also for SHAKE).

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> Having spent a few more minutes thinking about this, I think I'd
> prefer a struct for the state, as this would allow the type checker to
> verify that things are being used correctly.

I fully agree. This is what I was about to reply to your earlier mail.

**Comment by dstebila** [comment]
Will this be an opaque struct so that consumers replacing this with their own SHA2 implementation can  still use their own (potentially different) struct?

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> Will this be an opaque struct so that consumers replacing this with
> their own SHA2 implementation can  still use their own (potentially
> different) struct?

It definitely should be, yes. Compiling the code with a different SHA2
implementation would then just need to include the header file of that
implementation with the definition of the struct.
