### ISSUE TITLE
Add duplicate consistency checks in both directions

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#174]
In discussion regarding #172, we concluded that duplicate consistency checks should happen in both directions. If only A checks consistency with B but not the other way around, changes to (only) B won't trigger CI checks for consistency with A.

**Comment by dstebila** [comment]
I don't think this is necessary. True, if the tests are run with PQCLEAN\_ONLY\_DIFFS or one of the other filters applied, then they might get skipped.  But on the full test runs, sufficient consistency checks would be triggered even if they're only unidirectional.

**Comment by mkannwischer** [comment]
Agreed. 
We should just make sure this is done before merging updates to existing schemes.
