### ISSUE TITLE
Rules for common tests in Makefile not compatible with BSD make.

### ISSUE THREAD

**Issue by ronnyws** [PQClean/PQClean#178]
The [ test Makefile](https://github.com/PQClean/PQClean/blob/9a8270669750c525c55c0cd63af1b4ff981a9a01/test/Makefile#L1) claims that it can be used with BSD make. However the [rule for the common tests](https://github.com/PQClean/PQClean/blob/9a8270669750c525c55c0cd63af1b4ff981a9a01/test/Makefile#L50) uses a percent pattern which is not supported by BSD make.

**Comment by dstebila** [comment]
Thanks very much!

**Comment by thomwiggers** [comment]
Perhaps we should also add a BSD container to the build process, if only for operating system coverage (don't think there's much value in running BSD-ppc etc).

**Comment by thomwiggers** [comment]
It's not possible to run FreeBSD containers on Linux as far as I can see... :disappointed:
