### ISSUE TITLE
namespacing extern variables?

### ISSUE THREAD

**Issue by leonbotros** [PQClean/PQClean#189]
I noticed that many implementations namespace extern variables.
I did not not namespace them and it did not report it.
Should extern variables be namespaced?

**Comment by thomwiggers** [comment]
In principle, they should be namespaced, as they're external symbols. I'm not sure why the tests don't catch them.

**However,** they should not exist in the first place. Global state makes code not thread-safe. See #168.

**Comment by thomwiggers** [comment]
I should clarify (after @mkannwischer made a good point) that if they're `const`, they are fine, but should still be `const`.
