### ISSUE TITLE
LEDA is too slow for the 'slow' valgrind tests

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#197]
We run the 'slow' tests on a schedule, and LEDA appears to break them because it takes too long under valgrind: https://circleci.com/gh/PQClean/PQClean/4983

**Comment by leonbotros** [comment]
I am aware of this problem, see #193.

**Comment by thomwiggers** [comment]
This got fixed, as #206 included a `no_output_timeout: 2h` change.

**Comment by leonbotros** [comment]
Nice job!

I'm also working on speeding this up using faster multiplication methods without variable-sized arrays. I was thinking about including this in a (hopefully more) constant-time "clean" implementation.
