### ISSUE TITLE
crypto-sign arguments in Dilithium

### ISSUE THREAD

**Issue by elsaVelazquez** [PQClean/PQClean#205]
To correctly return 0 for computing signed message, Line 307 in sign.c, Dilithium 3, explanation should read:
- const unsigned char *sk: pointer to bit-packed secret key
(vs to public key)

**Comment by joostrijneveld** [comment]
I think you're referring to line 370, which is indeed wrongfully mixing the secret and public key. It should mention the public key, though (see line 378), as this is the public verification operation.

https://github.com/PQClean/PQClean/blob/04a0dbfb72ad6ea9ba220553bba233f352027f6f/crypto_sign/dilithium3/clean/sign.c#L370-L378

**Comment by elsaVelazquez** [comment]
yes, you are correct @joostrijneveld, that is what I meant

**Comment by thomwiggers** [comment]
Thanks for reporting this, PR #211 fixes this.
