### ISSUE TITLE
Enforcing code style

### ISSUE THREAD

**Issue by henrydcase** [PQClean/PQClean#21]
How about introducing code style checks, something a la gofmt from Golang (I remember someone has mentioned it during workshop)? This could be done by one of the tools below. Format checks could be run by CI for each PR.

* http://astyle.sourceforge.net/
* https://clang.llvm.org/docs/ClangFormat.html

**Comment by dstebila** [comment]
Yes, this is a good idea.  We already have a .clang-format style file.  As far as I can tell, there's no way for clang-format to say "these files don't match the style" -- instead you would run clang-format and see if the files change.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> Yes, this is a good idea.  We already have a .clang-format style file.
> As far as I can tell, there's no way for clang-format to say "these
> files don't match the style" -- instead you would run clang-format and
> see if the files change.

Well, that would be an easy test to implement. It's maybe a bit of a
question how strict we want to be in terms of coding style. Maybe during
round 2, while we still have 26 schemes to deal with, be a bit more
inclusive (i.e., lenient) on coding style and prioritize completeness?

**Comment by thomwiggers** [comment]
Already implemented:

https://github.com/PQClean/PQClean/blob/master/Makefile#L95

**Comment by henrydcase** [comment]
suggestion here would be run ``clang-format`` in docker. that's because locally someone may have different version of clang which won't result in same formatting. Here how it was done in some of my other projects:
https://github.com/riboseinc/rnp/blob/d4f56197b8ab877aaee1706c8ad820ce3d66f3dc/git-hooks/pre-commit.sh#L58

**Comment by thomwiggers** [comment]
Yeah, we just ran into that issue between @cryptojedi and my versions of Clang-format. Commit fe4651483606ed2dbc255597d015e5a90d9d6fa5 adds my full `-dump-config` output to hopefully stabilize it a bit.

I wouldn't like doing it via Docker though, because setting up docker and having to run code as root (if you're in the docker group, you're root) is very annoying.

**Comment by dstebila** [comment]
We ran into the same problem with OQS as well.  We just fixed a version of clang-format and its behaviour seemed to be consistent within a version but across platforms.
