### ISSUE TITLE
Un-align input byte arrays

### ISSUE THREAD

**Issue by cryptojedi** [PQClean/PQClean#24]
We might want to make sure that all input byte arrays (keys, ciphertext, message
etc.) are not aligned to catch if code makes any kind of assumptions about data
alignment. Could simply align one byte more and OR address with 1.

**Comment by dstebila** [comment]
Not sure I understand.  Would we artificially add a single byte prefix to each input? Or would we change the function API so that the first input is a dummy uint8_t?  Either of these seem like they would yield code that isn't a true implementation of the algorithm.

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> Not sure I understand.  Would we artificially add a single byte prefix
> to each input? Or would we change the function API so that the first
> input is a dummy uint8_t?  Either of these seem like they would yield
> code that isn't a true implementation of the algorithm.

Only modify the test functions, along the following lines:

uint8_t sk[CRYPTO_SECRETKEYBYTES+1];
uint8_t *skp = sk|1;

Call API functions with skp as argument instead of sk.

**Comment by dstebila** [comment]
If we changed the canary in functest.c to have odd length, would that suffice?

**Comment by cryptojedi** [comment]
Douglas Stebila <notifications@github.com> wrote:
> If we changed the canary in functest.c to have odd length, would that suffice?

No, then the pointers that we're passing to API functions might still be
aligned. Imagine now a scheme using a movdqa instruction to pick up data
from that point, i.e., assuming that this pointer is aligned. This is
something that is forbidden by the API (because the API does not
guarantee any alignment of addresses that are passed to the functions),
but our tests at the moment wouldn't catch it.
