### ISSUE TITLE
implicit declaration of function ‘aes256_keyexp’

### ISSUE THREAD

**Issue by baentsch** [PQClean/PQClean#283]
A recent merge somehow created a downstream problem in `liboqs` when merging in the latest PQClean code and compiling with `-Werror=implicit-function-declaration`:

Does this ring a bell or should I investigate further within `PQClean`?

**Comment by thomwiggers** [comment]
See #279

**Comment by thomwiggers** [comment]
`aes*_keyexp` got split into algortithm-specific variants. You need to update your `pqclean_shim.c`.
