### ISSUE TITLE
What to do about NIST seedexpander?

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#292]
As observed by @baentsch in https://github.com/open-quantum-safe/liboqs/issues/709#issuecomment-621790096, LEDA and HQC both make use of NIST seedexpander. But they do so in different ways: LEDA has it [internal to the implementation](https://github.com/PQClean/PQClean/blob/master/crypto_kem/ledakemlt12/leaktime/rng.c) whereas [HQC includes it](https://github.com/PQClean/PQClean/blob/a8a263de816e04537e586dce21a1c665f51570f4/crypto_kem/hqc-128-1-cca2/leaktime/kem.c) from [PQClean's common](https://github.com/PQClean/PQClean/blob/master/common/nistseedexpander.h).  We should pick one way and just do that.  Which way to go?

**Comment by thomwiggers** [comment]
I think you're right and we should refactor it out of the schemes; as it was part of the "NIST API" apparently

**Comment by thomwiggers** [comment]
LEDA has been removed and that's the only one that doesn't use it from the API.
