### ISSUE TITLE
LEDA is broken; update LEDA to version 3

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#294]
LEDA 2.1 as we have in our repo is broken (https://eprint.iacr.org/2020/455); we should update (see https://groups.google.com/a/list.nist.gov/forum/?utm_medium=email&utm_source=footer#!msg/pqc-forum/LZXD_WFqzs8/zg3TUKjWBQAJ). 

See also https://github.com/rustpq/pqcrypto/issues/8

**Comment by dstebila** [comment]
LEDAcrypt not in round 3.

**Comment by thomwiggers** [comment]
Hmm, should we remove LEDA then, considering the current implementation is insecure and we are probably not motivated to update?
