### ISSUE TITLE
META.yml for Kyber512 broken?

### ISSUE THREAD

**Issue by baentsch** [PQClean/PQClean#296]
Hi, unlike all other Kyber META.yml files, the one for Kyber512 does not list AES as a build prerequisite for the 'avx2' variant: https://github.com/PQClean/PQClean/blob/a8a263de816e04537e586dce21a1c665f51570f4/crypto_kem/kyber512/META.yml#L31 

This now led to a downstream error in `liboqs` (which uses this file to define build parameters).

Could you please check whether this is indeed an error and correct it (bring it in line with the other KyberXXX `META.yml`) or let me know whether Kyber512-avx2 can indeed do without AES? 
The problem I see is that it depends on Keccak which in turn, if built with AVX2 support, _also_ needs AES support; thus, Kyber-avx2 transitively also needs AES.

Thanks in advance for checking.

**Comment by thomwiggers** [comment]
`crypto_kem/kyber512/avx2` builds fine without `-maes`, as evidenced by the `Makefile`, and similarly the `Makefile` for `common/keccak4x` only uses `-mavx2`.

**Comment by thomwiggers** [comment]
Do the import scripts in ``liboqs`` maybe somehow confuse ``kyberXXX-90s`` and ``kyberXXX``?

**Comment by baentsch** [comment]
> Do the import scripts in liboqs maybe somehow confuse kyberXXX-90s and kyberXXX?

No, they don't. The problem was indeed an 'over-eager' "sha3x4" build in liboqs (unecessarily requiring AES) in combination with my confusion about the different META.yml's between Kyber 512 vs Kyber768/1024 (as now fixed by #297 : Thanks @thomwiggers ). Issue resolved.
