### ISSUE TITLE
Define directory structure

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#3]
We need to figure out the directory structure so we can then include the first schemes. This is also necessary before we can start to figure out our build and testing scripts, as they will need to do some looping over the directory structure.

For to be able to just copy in files into SUPERCOP, we'd need one directory per parameter set.

**Comment by thomwiggers** [comment]
Current proposal:

* `PQClean/`
  * `Makefile`
  * `crypto_kem/`
    * `kyber512/`
       * source code of the scheme: `*.c` and `*.h` files.
       * `META.yaml`
    * `test.c` – test various
  * `crypto_kem/`
    * `Dilithium-III/`
      * `META.yml`
      * `*.c / *.h`
    * `test.c`  – Tests various use scenarios, functional tests
    * `testvectors.c` – Tests key generation, signature generation, consistency between platforms
  * `common/`
     * `aes.c/h`
     * `randombytes.c/h`
     * `sha2.c/h`
     * `fips202.c/h`
  * `.travis.yml`
  * `scripts/`  -  will contain various utility scripts, may be referenced by the Makefile
    * `run-testvectors.py`
    * `functest.sh`


The Makefile should support operations such as 

```
$ make kem_functest SCHEME=kyber768
```
where the `Makefile` would contain something like:

```Makefile
functest: crypto_kem/test.c crypto_kem/$(SCHEME)/*.c
  $(CC) $(CFLAGS) -I common/ $^ -o bin/functest_$SCHEME
```

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> Current proposal:
> 
> * `PQClean/`
>   * `Makefile`
>   * `crypto_kem/`
>     * `kyber512/`
>        * source code of the scheme: `*.c` and `*.h` files.
>        * `META.yaml`
>     * `test.c` – test various
>   * `crypto_kem/`
>     * `Dilithium-III/`
>       * `META.yml`
>       * `*.c / *.h`
>     * `test.c`  – Tests various use scenarios, functional tests
>     * `testvectors.c` – Tests key generation, signature generation, consistency between platforms
>   * `common/`
>      * `aes.c/h`
>      * `randombytes.c/h`
>      * `sha2.c/h`
>      * `fips202.c/h`
>   * `.travis.yml`
>   * `scripts/`  -  will contain various utility scripts, may be referenced by the Makefile
>     * `run-testvectors.py`
>     * `functest.sh`
> 
> 
> The Makefile should support operations such as 
> 
> ```
> $ make kem_functest SCHEME=kyber768
> ```
> where the `Makefile` would contain something like:
> 
> ```Makefile
> functest: crypto_kem/test.c crypto_kem/$(SCHEME)/*.c
>   $(CC) $(CFLAGS) -I common/ $^ -o bin/functest_$SCHEME
> ```

There needs to be one Makefile per implementation of each primitive,
without any external dependencies. This should build just pqclean.a (or,
alternatively something like kyber512_clean.a). I would place all tests
in a test/ directory under the root directory. Also, as Douglas pointed
out, we want support for multiple implementations per scheme, so
something like

PQClean/
  * crypto_kem/
    * kyber768/
      * clean/
        * .c and .h files of kyber768
        * Yaml META file
        * LICENSE file (if not inside Yaml)
        * Makefile for kyber768_clean.a

**Comment by dstebila** [comment]
See PR #13 and #14 for approaches to Makefiles for individual schemes.

**Comment by cryptojedi** [comment]
Reached consensus on this one
