### ISSUE TITLE
Fixed-sized integer types instead of `char` and `int`

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#31]
Henry Case <notifications@github.com> wrote:
> henrydcase commented on this pull request.
> 
> 
> 
> > @@ -23,9 +23,9 @@ void PQCLEAN_KYBER768_poly_compress(unsigned char *r, const poly *a) {
>              t[j] = (((PQCLEAN_KYBER768_freeze(a->coeffs[i + j]) << 3) + KYBER_Q / 2) / KYBER_Q) & 7;
>          }
>  
> -        r[k]     =  t[0]       | (t[1] << 3) | (t[2] << 6);
> -        r[k + 1] = (t[2] >> 2) | (t[3] << 1) | (t[4] << 4) | (t[5] << 7);
> -        r[k + 2] = (t[5] >> 1) | (t[6] << 2) | (t[7] << 5);
> +        r[k]     = (unsigned char)( t[0]       | (t[1] << 3) | (t[2] << 6));
> 
> nit: the README.md says ``All integer types are of fixed size, using stdint.h types (including uint8_t instead of unsigned char)``

This still has to be fixed everywhere in the code, if we want to really
require it.

_Originally posted by @cryptojedi in https://github.com/PQClean/PQClean/pull/29#issuecomment-463914273_

**Comment by henrydcase** [comment]
I've seen there is also ``u8`` type used somewhere in the code. But I wonder - what's real motivation for "not using" ``unsigned char``? The only 2 things I can think of:
* ``unsigned char`` doesn't have to be 8-bit wide, but AFAIK it's always is
* ``uint8_t`` makes code cleaner (shows an intent)

Something else?

**Comment by thomwiggers** [comment]
FWIW, according to Wikipedia:

> POSIX requires char to be exactly eight bits in size.

**Comment by cryptojedi** [comment]
Henry Case <notifications@github.com> wrote:
> I've seen there is also ``u8`` type used somewhere in the code. But I wonder - what's real motivation for "not using" ``unsigned char``? The only 2 things I can think of:
> * ``unsigned char`` doesn't have to be 8-bit wide, but AFAIK it's always is
> * ``uint8_t`` makes code cleaner (shows an intent)
> 
> Something else?

The idea would be to only allow fixed-size integer types everywhere,
i.e., forbid "int", "short", "long", and "long long"; only use size_t
(admittedly also variable size) for indexing, stdint fixed-width types
everywhere else. Using uint8_t would then be just consistently following
this rule

**Comment by henrydcase** [comment]
Makes sense. Now, I vaguely recall TI compiler having 16-bit char.

**Comment by joostrijneveld** [comment]
For the sake of documentation: a related issue that came up in discussion yesterday was the fact that some platforms interpret `char` as `signed char`, while others treat it as `unsigned char`.

There are compiler flags `-fsigned-char` and `-funsigned-char` for GCC that force either one of the two, but nothing obvious that explicitly warns about its use. We'll probably have to do some more complicated parsing (or #define-magic?) to check for types like `long long` anyway.

**Comment by thomwiggers** [comment]
We also decided to postpone this to (probably) round three or after, because it seems like a lot of work that we did not want to put on all of the second-round candidates.

**Comment by dstebila** [comment]
See discussion in #79
