### ISSUE TITLE
ntruhrss701 fails to compile

### ISSUE THREAD

**Issue by mouse07410** [PQClean/PQClean#318]
```
as -o poly_s3_to_rq.o poly_s3_to_rq.s
poly_s3_to_rq.s:3116:1: error: unsupported symbol modifier in branch relocation
call PQCLEAN_NTRUHRSS701_AVX2_poly_Rq_mul_x_minus_1@plt
^
make: *** [poly_s3_to_rq.o] Error 1
```

This issue has been fixed in upstream: https://github.com/jschanck/ntru/commit/4e5ed14449c93496b74c2a0ebb0b52031323dd2c

Please incorporate this fix (and other updates too ;).

**Comment by thomwiggers** [comment]
PR #316 was already merged a few days ago.

**Comment by thomwiggers** [comment]
Ah, this is a different problem. @jschanck, will you create another PR from your script?
