### ISSUE TITLE
Please make test/Makefile configurable

### ISSUE THREAD

**Issue by mouse07410** [PQClean/PQClean#320]
This is what I'm asking for:
```diff
diff --git a/test/Makefile b/test/Makefile
index eeb09ebf..8856b25a 100644
--- a/test/Makefile
+++ b/test/Makefile
@@ -1,9 +1,9 @@
 # This Makefile can be used with GNU Make or BSD Make
 
 # override as desired
-TYPE=kem
-SCHEME=kyber768
-IMPLEMENTATION=clean
+TYPE?=kem
+SCHEME?=kyber768
+IMPLEMENTATION?=clean
 
 SCHEME_DIR=../crypto_$(TYPE)/$(SCHEME)/$(IMPLEMENTATION)
 SCHEME_UPPERCASE=$(shell echo $(SCHEME) | tr a-z A-Z | sed 's/-//g')
```

**Comment by thomwiggers** [comment]
Why? That makefile is only for testing, subject to change and can easily be overridden by specifying options on the command line:

```
make SCHEME=kyber768
```

**Comment by mouse07410** [comment]
> these options can already easily be overridden by specifying options on the command line:

I did not realize that. Thank you!

I still prefer the form I suggested as it is clearer for the casual observer (like myself), but your way works 100%.
