### ISSUE TITLE
Build failures in HQC

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#327]
https://github.com/open-quantum-safe/liboqs/pull/835 encounters build failures with the current (383874f4082ab26a234e0e3428ee0f419e008765) version of PQClean's HQC.  I've observed at least the following problems:

### 1. pclmul instruction

```
../src/kem/hqc/pqclean_hqc-rmrs-192_avx2/gf2x.c:100:50: error: '__builtin_ia32_pclmulqdq128' needs target feature pclmul
    DD1 = _mm_xor_si128(_mm_xor_si128(DD0, DD2), _mm_clmulepi64_si128(AAlpAAh, BBlpBBh, 0));
                                                 ^
/usr/lib64/clang/9.0.1/include/__wmmintrin_pclmul.h:45:13: note: expanded from macro '_mm_clmulepi64_si128'
  ((__m128i)__builtin_ia32_pclmulqdq128((__v2di)(__m128i)(X), \
            ^
```

This can be fixed on liboqs by adding -mpclmul to the build scripts.  But presumably this should be in HQC's META.yml files as well?

### 2. gen_matrix in parameters.h not namespaced

Once the pclmul issue is fixed, I get

```
duplicate symbol '_gen_matrix' in:
    lib/liboqs.a(code.c.o)
duplicate symbol '_gen_matrix' in:
    lib/liboqs.a(code.c.o)
```

This seems to be because code.c in the various HQC variants each includes its respective gen\_matrix.h, which includes a non-namespaced global variable `gen_matrix`.  This should be namespaced.  (Does this indicate a failure in the PQClean tests for globally namespaced symbols?)

**Comment by dstebila** [comment]
@jschanck

**Comment by thomwiggers** [comment]
> Does this indicate a failure in the PQClean tests for globally namespaced symbols?

The test does ignore symbols defined in the data segment. In general it makes a bit of a weird selection...

**Comment by dstebila** [comment]
Making progress!  Still not quite there though.  Now we're getting build failures about shadowed declarations; see e.g. https://app.circleci.com/pipelines/github/open-quantum-safe/liboqs/1079/workflows/5a0b66b7-69a2-4b60-9099-ae0273547ec7/jobs/10897.  As far as I can tell, the PQClean test/Makefile has `-Wshadow`, but the Makefiles in the individual crypto\_kem and crypto\_sign folders do not.
