### ISSUE TITLE
Alignment problems in AVX2 implementation of HQC-RMRS-256

### ISSUE THREAD

**Issue by RW-sec** [PQClean/PQClean#375]
While updating PQClean inside of [rustpq/pqcrypto](https://github.com/rustpq/pqcrypto) I stumbled upon a possible bug in the _compute_syndromes()_ function of `reed_solomon.c`.
I tried to run the tests with `cargo test`, but it failed for the AVX2 implementation of HQC-RMRS-256 with a `Segmentation fault`.
Please see attached image:
![Screenshot from 2021-02-25 17-44-00](https://user-images.githubusercontent.com/79637734/109292717-19666580-782b-11eb-8a36-d27fbc4a880a.png)
Please let me know, if you need further information.

**Comment by thomwiggers** [comment]
That looks like an alignment issue...

**Comment by thomwiggers** [comment]
```c
void compute_syndromes(uint16_t *syndromes, uint8_t *cdw) {
    __m256i *syndromes256 = (__m256i *) syndromes;
```

Yeah, that's a super-illegal cast.
