### ISSUE TITLE
non constant-time code

### ISSUE THREAD

**Issue by kriskwiatkowski** [PQClean/PQClean#394]
Seems to me that, this check is not constant time.

https://github.com/PQClean/PQClean/blob/bc717609964c3df9e8fd8848d450a48c5cc3a71d/crypto_sign/dilithium2/clean/sign.c#L291

**Comment by mkannwischer** [comment]
Why do you want to do this check in constant time? Both c and c2 are public anyway.

**Comment by kriskwiatkowski** [comment]
ah, right. my bad
