### ISSUE TITLE
Issues with HQC AVX2 implementation

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#397]
A possible continuation of #375, I'm still getting spurious failures with HQC's avx2 implementations in my Rust wrapper around PQClean. Of course, in some version of Murphy's law, I'm not getting the failures when I run the unit tests under gdb...

```
cargo test -p pqcrypto-hqc
---- ffi::test_hqcrmrs256_avx2::test_ffi stdout ----
thread 'ffi::test_hqcrmrs256_avx2::test_ffi' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `-1`', pqcrypto-hqc/src/ffi.rs:353:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    ffi::test_hqcrmrs256_avx2::test_ffi

test result: FAILED. 8 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s
```

**Comment by thomwiggers** [comment]
It doesn't seem to happen when I don't run the tests multi-threaded...

**Comment by jschanck** [comment]
New HQC code was announced on pqc-forum a few days ago. I'll take a shot at integrating it.

**Comment by thomwiggers** [comment]
This hasn't been a problem for a while now I think.
