### ISSUE TITLE
Name inconsistencies in crypto_kem/META.yml files

### ISSUE THREAD

**Issue by xvzcf** [PQClean/PQClean#400]
Since, for example, the `name` field is `FrodoKEM-640-SHAKE` in  [frodokem640shake/META.yml](https://github.com/PQClean/PQClean/blob/master/crypto_kem/frodokem640shake/META.yml#L1)  and is `Classic McEliece 6688128` in [mceliece6688128f/META.yml](https://github.com/PQClean/PQClean/blob/master/crypto_kem/mceliece6688128f/META.yml#L1), shouldn't `name` in, say, [ntruhps2048509/META.yml](https://github.com/PQClean/PQClean/blob/master/crypto_kem/ntruhps2048509/META.yml#L1) be `NTRU-HPS-2048-509`?

**Comment by thomwiggers** [comment]
We've never really given that field much thought I think. It would probably be better to use the "pretty" names as used in the submissions, but that would also mean updating `CRYPTO_ALGNAME` as [that is verified to match](https://github.com/PQClean/PQClean/blob/master/test/test_metadata_sizes.py#L41).

**Comment by xvzcf** [comment]
I see. I could put up a PR making the switch to the pretty names, but I'm guessing changing `CRYPTO_ALGNAME` here would necessitate also changing it upstream?

**Comment by thomwiggers** [comment]
We can make changes downstream (here) just fine, we don't upstream a lot...

**Comment by thomwiggers** [comment]
⚰️  RIP Frodo, you will be missed.
