### ISSUE TITLE
Stack pointer gets corrupted on (fire|light)saber keygen

### ISSUE THREAD

**Issue by Martyrshot** [PQClean/PQClean#431]
I'm currently having an issue when running `indcpa_kem_keypair()` using the aarch64 optimized versions of the saber family. The frame pointer appears to get corrupted when `PQCLEAN_LIGHTSABER_AARCH64_asm_asymmetric_mul` is called, and thus causes a segmentation fault when `indcpa_kem_keypair()` returns.

Line in lightsaber where frame pointer first gets corrupted:
https://github.com/PQClean/PQClean/blob/f365dcfe69f15325443ce65df9798e42816f78e9/crypto_kem/lightsaber/aarch64/SABER_indcpa.c#L122

I'm experiencing this issue on Ubuntu, both with gcc-10 and clang-10, and the issue also occurs on apple M1 using appleclang.

Any help would be appreciated, and thanks in advance!

**Comment by Martyrshot** [comment]
Small update: After doing a little bit of digging, it looks like the stack pointer is getting corrupted after `PQCLEAN_LIGHTSABER_AARCH64_asm_asymmetric_mul()` is called. The frame pointer issue can be avoided by not using `fno-omit-frame-pointer`.

**Comment by vincentvbh** [comment]
Hi @Martyrshot. 
Can you perform a quick check if changing line 17 into` ldr w27, [x3, #4]` and line 20 into `dup v29.4S, w27` solves the issue?
Will definitely be more careful on avoiding x29.

Thanks for spotting this,
Vincent

**Comment by Martyrshot** [comment]
Hi Vincent,
This does resolve the issue I was experiencing. I have tested it on an M1, and an AWS Neoverse-N1. On the AWS instance, I have tested with both clang-10 and gcc-10.

Thanks!
-Jason

**Comment by mkannwischer** [comment]
Thanks @Martyrshot, @vincentvbh. We'll get that fixed upstream and will open a PR to PQClean later today.
