### ISSUE TITLE
Status of calls to `randombytes` are not checked

### ISSUE THREAD

**Issue by jboillot** [PQClean/PQClean#445]
Hello,
I am not sure if this problem is in the scope of this project but currently the status returned by common function `randombytes` is not checked.
Would it be possible to abruptly stop the program when such a case arises?

**Comment by thomwiggers** [comment]
I'm afraid none of the reference implementations does this right now. I suppose it's possible to add an abort or panic inside the `randombytes` function; if you need this I would suggest doing this in your own project. The `common` files aren't necessarily the best implementations of any of the primitives.

**Comment by jboillot** [comment]
Thank you for your answer!
Jérôme
