### ISSUE TITLE
Update SPHINCS+

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#446]
https://github.com/sphincs/sphincsplus/pull/28

**Comment by thomwiggers** [comment]
Upstream also changed the names slightly. I think we should probably follow that for PQClean but downstream projects might want to adapt...

**Comment by thomwiggers** [comment]
some prep work at https://github.com/sphincs/sphincsplus/pull/37

**Comment by thomwiggers** [comment]
More work at https://github.com/sphincs/sphincsplus/pull/40

**Comment by dstebila** [comment]
What's the next step here?  Are the upstream PRs just waiting for review (if so I can review) or is there more work to be done?

**Comment by thomwiggers** [comment]
Yeah it would be nicest if those upstream PRs got merged. I'll bump the PR.
