### ISSUE TITLE
crypto_kem/hqc-rmrs-128/avx2/reed_muller.c: violating C aliasing rules

### ISSUE THREAD

**Issue by vt-alt** [PQClean/PQClean#453]
The bug iin `crypto_kem/hqc-rmrs-128/avx2/reed_muller.c` is found in `liboqs`—the tests suddenly fail when compiled on GCC-12, **because** for GCC this use of `tmp` is violating C aliasing rules and producing undefined behavior (thus not even showing correct compile warning):

https://github.com/PQClean/PQClean/blob/12cb25a7f04daa8c76870e6ae3ce85b4ecacd044/crypto_kem/hqc-rmrs-128/avx2/reed_muller.c#L336

It seems such indexed access to `tmp` is producing garbage. See this small discussion for details: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=106470

**Comment by thomwiggers** [comment]
Okay so it seems we need to replace that with ``_mm256_extract_epi16(tmp, i)``? This probably happens in a bunch of places...

**Comment by thomwiggers** [comment]
> _mm256_extract_epi16(tmp, i) will not work because i should be immediate value.

ugh, this is why we can't have nice things.

**Comment by thomwiggers** [comment]
Not sure what you mean by "proper cast"; we don't want to use `__aligned__` or other GNU compiler extensions in PQClean. (This does make AVX2 code horribly messy...)

**Comment by vt-alt** [comment]
Andrew suggested to use
```
        for (size_t i = 0; i < 16; i++) {
                typedef __attribute__((vector_size(sizeof(__m256i)) )) uint16_t myvector_t;
                myvector_t t;
                t = (myvector_t)tmp;
                printf(" %04x", t[i]);
        }
```
This should be gcc and clang compatible. Don't know about other compilers you want to support, though (if they support vector types).

Also, I found that `avxintrin.h` have `__v16hu` type which should work too, but also I don't know how much other compilers support it (icc? msvc?). Nor I know performance impact of such cast (what is it copies whole register to a memory).

Using `extract_epi16` seems most portable. Performance impact is unclear but at least it's not buggy.

**Comment by thomwiggers** [comment]
It works in Clang because it implements all of the GNU extensions. ``__attribute__` isn't part of the C standard afaik and not supported under MSVC.

Now, I know that all of the assembly that we have also isn't supported on Windows; but we ban `__attribute__` because a) it makes migrating code to MSVC harder and b) it breaks `pycparser` which we use in CI.

**Comment by vt-alt** [comment]
Another option, it seems, is to unroll the loop manually like this:
```diff
@@ -331,10 +331,26 @@ inline uint32_t find_peaks(__m256i *transform) {
         tmp = _mm256_or_si256(tmp, _mm256_and_si256(vect_mask, transform[i]));
     }
     result = 0;
-    for (size_t i = 0; i < 16; i++) {
-        mask = ~(uint32_t) ((-(int64_t)(i ^ message % 16)) >> 63);
-        result |= mask & ((uint16_t *)&tmp)[i];
-    }
+#define UNROLLED_X(i) \
+        mask = ~(uint32_t) ((-(int64_t)(i ^ message % 16)) >> 63); \
+        result |= mask & _mm256_extract_epi16(tmp, i);
+    UNROLLED_X(0)
+    UNROLLED_X(1)
+    UNROLLED_X(2)
+    UNROLLED_X(3)
+    UNROLLED_X(4)
+    UNROLLED_X(5)
+    UNROLLED_X(6)
+    UNROLLED_X(7)
+    UNROLLED_X(8)
+    UNROLLED_X(9)
+    UNROLLED_X(10)
+    UNROLLED_X(11)
+    UNROLLED_X(12)
+    UNROLLED_X(13)
+    UNROLLED_X(14)
+    UNROLLED_X(15)
+#undef UNROLLED_X
     message |= (0x8000 & ~result) >> 8;
     return message;
 }

```
