### ISSUE TITLE
 Upgrade Classic McEliece to NIST round 4 specification

### ISSUE THREAD

**Issue by faern** [PQClean/PQClean#459]
Hi! Are there any plans to upgrade the Classic McEliece KEM to the [round 4 specification](https://classic.mceliece.org/nist.html)? I suppose it will be done. But I could not find any issue or PR on it. So I figured I could create this tracking issue.

**Comment by thomwiggers** [comment]
Coincidentally, I started work on this today. Cleaning up Classic McEliece is lots of work though, so it might be a little bit.
