### ISSUE TITLE
Malleable Falcon signatures, may need upgrade to v1.2 spec

### ISSUE THREAD

**Issue by WizardOfMenlo** [PQClean/PQClean#464]
Hi there,

The clean/avx2 implementations of Falcon-512 and Falcon-1024 seem to be unaligned with some changes introduced in v1.2 of the spec.

In particular, the implementation of the signature verification algorithm currently in PQClean accepts mauled signatures due to how `comp_decode` in `codec.c` is implemented. I attached an example program for ease of inspection.

Following Section 3.11.2 and Algorithms 17-18 in the Falcon spec v1.2, I believe that in order to enforce a unique encoding of compressed signatures, the decode implementation should not accept 100000001 ("-0") as a valid encoding of 0, and should check that signatures are padded using zeroes.

I have also raised the [same issue](https://github.com/open-quantum-safe/liboqs/issues/1315) in LibOQS for completeness.

Kind Regards,
Giacomo Fenzi

Attached bug: [bug.c](https://gist.github.com/WizardOfMenlo/59e6e0457f94bf5caf13909f319007de)

**Comment by thomwiggers** [comment]
I have updated the code to the latest version in SUPERCOP, but I don't see any changes to codec.c. So this might not fix the actual issue...

**Comment by thomwiggers** [comment]
Hi @pornin, if I'm not mistaken I think you had a generator for SUPERCOP and PQClean versions of the source code at some point. Does that still exist, and would you have time and be willing to submit updates? 

Alternatively I will just have to dig out the updates to `comp_decode`.

**Comment by WizardOfMenlo** [comment]
You might want to look at [codec.c](https://falcon-sign.info/impl/codec.c.html) from Falcon reference. The function involved is `comp_decode` in particular, and the two added checks are at line 458 and 468. This seems to fix this particular issue (from my testing), but cannot guarantee that it is the only change for v1.2 spec compliance.
