### ISSUE TITLE
Falcon produces invalid signatures

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#477]
It seems I've introduced a bug in the Falcon update (#476) while patching some PQClean complaints. I'm currently tracking them down.

**Comment by thomwiggers** [comment]
The Falcon-1024 signatures sometimes don't verify correctly. I've dissected all of my changes but the thing that seems to cause it is the new, smaller CRYPTO_BYTES value of 1280 (originally it was 1330). Weirdly, it doesn't seem to happen (maybe because it is probabilistic) in Falcon-512 which went from 690 to 666.
If I change CRYPTO_BYTES to 1284 or more, it seems to be working again. This kind of suggests an encoding problem, but I can't really tell the difference between falcon.h and what pqclean-api.c or nist-api.c is doing, and it also looks similar to what the spec requires...

**Comment by thomwiggers** [comment]
I've received the source code, and the script from which the PQClean implementation was generated, from @pornin. I'm not sure if the code at https://falcon-sign.info/impl/README.txt.html is so much older, but the code that's in the NIST packages definitely seems out of date.

**Comment by thomwiggers** [comment]
I've worked with Pornin a bit and we found some problems with how the signatures are encoded, which don't seem to be present in the upstream API. Probably the PQClean API wrapper needs to be re-implemented, which will take some time.

**Comment by dstebila** [comment]
@thomwiggers do you think this is likely to address problems we were encountering in https://github.com/open-quantum-safe/liboqs/issues/1390?
