### ISSUE TITLE
Migrate CI containers off Docker hub

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#481]
The CI containers are hosted by docker hub, but they're sunsetting free accounts. I'm not exactly sure if that means that we can not push to the public repos that we use for CI anymore, but they're talking about rate limiting our accounts which may affect us (we have pulled almost 1.5 million times from Docker hub!). The rate limit for personal accounts is only 200 pulls per 6 hours: our CI will exceed this.

This starts April 14

**Comment by dstebila** [comment]
Docker has an open source program for which we might be eligible. https://www.docker.com/community/open-source/application/

**Comment by Vad1mo** [comment]
If, for some reason, the Docker-Sponsored Open-Source Program isn't working out, we are happy to help you out. We operate a Harbor-based [container registry as a service ](https://container-registry.com/)that has many benefits over most of the other registries out there.

There are also features regarding containerized image distribution, that might be valuable too as well.

**Comment by thomwiggers** [comment]
Thanks, but we can probably just push them to Github's container registry if necessary.

**Comment by thomwiggers** [comment]
Docker did a 180 on this
