### ISSUE TITLE
Calculation for size of unsigned char array results in float?

### ISSUE THREAD

**Issue by Muzosh** [PQClean/PQClean#491]
https://github.com/PQClean/PQClean/blob/d742438e5c541958bfd58070cd8668d757d88e07/crypto_sign/sphincs-haraka-256s-simple/clean/wots.c#LL69C1-L69C71

SPX_WOTS_LEN2 is defined as 3 ([here](https://github.com/PQClean/PQClean/blob/d742438e5c541958bfd58070cd8668d757d88e07/crypto_sign/sphincs-haraka-256s-simple/clean/params.h#LL30C1-L30C24))
SPX_WOTS_LOGW is defined as 4 (couple of lines before)

`(SPX_WOTS_LEN2 * SPX_WOTS_LOGW + 7) / 8` then equals 2.375, thus the array creation fails, because it obviously requires integer number.

Am I completely stupid and overlooking something?

**Comment by Muzosh** [comment]
I see that these values are taken from [here](https://github.com/sphincs/sphincsplus/blob/c379675505ac42d8c92e857badd651f25e5fef3f/ref/params/params-sphincs-haraka-256s.h#LL24C1-L54C7), just hard coded for `SPX_WOTS_W = 16`. However I see that PQClean's tests are working fine. How so?

**Comment by Muzosh** [comment]
Ok, so I guess array initialization with float size just floors the number automatically.

**Comment by thomwiggers** [comment]
In C, integers do not get promoted to floats, so division truncates.
