### ISSUE TITLE
LICENSE files for Dilithium and Kyber aarch64 implementations only mention CC0

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#498]
A related question: While https://github.com/PQClean/PQClean/pull/488 added license headers to individual source files of Kyber/Dilithium/aarch64, the main [LICENSE](https://github.com/PQClean/PQClean/blob/master/crypto_kem/kyber1024/aarch64/LICENSE) files mention only CC0. Was this an oversight or intentional?

_Originally posted by @bhess in https://github.com/PQClean/PQClean/issues/495#issuecomment-1651165551_

**Comment by vincentvbh** [comment]
Oversight.
