### ISSUE TITLE
PQCLEAN_DILITHIUM3_CLEAN_polyz_unpack and PQCLEAN_DILITHIUM5_CLEAN_polyz_unpack: Bug found?

### ISSUE THREAD

**Issue by HeHa112** [PQClean/PQClean#529]
Hello everyone,

during the code review of the functions PQCLEAN_DILITHIUM5_CLEAN_polyz_unpack and PQCLEAN_DILITHIUM3_CLEAN_polyz_unpack I noticed a discrepancy. 
The positions r->coeffs[2 * i + 0] and r->coeffs[2 * i + 1] are filled in the for loop. However, the &= 0xFFFFF is only made at position r->coeffs[2 * i + 0]. Could it be that the second &= 0xFFFFF is intended for r->coeffs[2 * i + 1]?

Best regards
Henrik

**Comment by thomwiggers** [comment]
It appears this question has also been asked upstream, and I think the comment there addresses your question: https://github.com/pq-crystals/dilithium/issues/63
