### ISSUE TITLE
Do the AVX2 implementations work on Windows?

### ISSUE THREAD

**Issue by aabmets** [PQClean/PQClean#531]
I see that there was an issue long ago about supporting AVX2 implementations on MacOS and Windows, but that issue thread did not answer whether the support had also been solved for the Windows platform. If Windows is supported, then how can I compile the source code with Visual Studio build tools? If not, then is there a plan to support AVX2 implementations on Windows?

**Comment by thomwiggers** [comment]
Some implementations support Windows and will have a `Makefile.Microsoft_nmake` file in the folder, plus the `META.yml` files will indicate support for Windows.  As the filename suggests, build using Microsoft NMake or just import the files into your own projects by copy-pasting them.

I think this is mainly SPHINCS+ though; most AVX2 implementations rely on assembly code, and assembler syntax is not portable: `gas` syntax is not understood by Microsoft's assembler.

As always, we're open to contributions to improve this situation for algorithms that are currently not supporting Windows.
