### ISSUE TITLE
About the parameters of Dilithium5

### ISSUE THREAD

**Issue by qinleiyong** [PQClean/PQClean#538]
In Dilithium5, shouldn't the parameter "PQCLEAN_DILITHIUM5_CLEAN_CRYPTO_BYTES" be 4595? But I saw that its value in "api.h" is 4627. Why is this?

**Comment by thomwiggers** [comment]
Adding to @mkannwischer's comment; the `api.h` in the pq-crystals/dilithium repository has not been updated to reflect the above change (even though `params.h` has).
