### ISSUE TITLE
Dead link for Dilithium in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rtjk** [PQClean/PQClean#550]
https://github.com/PQClean/PQClean/blob/8e221ae797b229858a0b0d784577a8cb149d5789/CONTRIBUTING.md?plain=1#L80-L85

#### Description
The URL for Dilithium in CONTRIBUTING.md is dead (404)

#### URL
https://github.com/thomwiggers/dilithium/tree/pqclean

**Comment by thomwiggers** [comment]
See #551
