### ISSUE TITLE
falcon-512 or falcon-padded-512?

### ISSUE THREAD

**Issue by leonbakadorov** [PQClean/PQClean#552]
What's the difference between falcon-512 and falcon-padded-512? I have a feeling that falcon-padded-512 is the older version (because it matches the signature size)?

It would be great if you could clarify the situation. Also, why did the signature length increase in falcon-512? Does this improve any properties? (Which ones?)

**Comment by cothan** [comment]
They are pretty much the same. You can see here: https://github.com/open-quantum-safe/liboqs/issues/1591 

Falcon-padded = Falcon fixed-length.  

https://github.com/open-quantum-safe/liboqs/issues/1561#issuecomment-1793699044

**Comment by leonbakadorov** [comment]
> They are pretty much the same. You can see here: [open-quantum-safe/liboqs#1591](https://github.com/open-quantum-safe/liboqs/issues/1591)
> 
> Falcon-padded = Falcon fixed-length.
> 
> [open-quantum-safe/liboqs#1561 (comment)](https://github.com/open-quantum-safe/liboqs/issues/1561#issuecomment-1793699044)

So why then is the variable length signature larger (longer)? Based on logic, a variable-length signature, on the contrary, should be shorter, i.e. less than 666 bytes. But she, on the contrary, is more. How is that? Or am I missing something?

**Comment by cothan** [comment]
Don't drill me. Feel free to comment on the #1591 and #1561.

**Comment by SWilson4** [comment]
The variable-length signature size is a maximum. Variable-length signatures will be shorter on average, but may be longer.
