### ISSUE TITLE
Dilithium 3 signature size different from specifications

### ISSUE THREAD

**Issue by SyedFahimuddinAlavi** [PQClean/PQClean#559]
I executed Dilithium 3 on RISC-V core and while verifying and writing report I saw that signature is 3342 bytes long. In specification of Dilithium it is mentioned that 3293 is size of signature. I then executed on my Linux PC and found that signature is wrong too and still 3342 bytes long. I am new to PQC so I am little confused.
I am attaching 
[nistkat_dilithium3_clean.zip](https://github.com/user-attachments/files/15925482/nistkat_dilithium3_clean.zip)

**Comment by mkannwischer** [comment]
The correct signature size is 3309.
That's what's listed in https://github.com/PQClean/PQClean/blob/master/crypto_sign/dilithium3/META.yml 
What you are seeing to be 3342 bytes long is a signed message consisting of a 33-byte message and a 3309-byte signature. 

The value 3293 that is in the [NIST draft](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.204.ipd.pdf) is wrong and NIST has clarified in [this statement](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/EKoI0u_PuOw/m/xQVnr5D0AQAJ). 

The reason for the added 16-bytes compared to round-3 Dilithium, can be found in Section 1.3.2 of the NIST draft
```
In order to ensure the properties noted in [6], ML-DSA increases the length of tr to 512 bits, and increases
the length of c˜ to 384 and 512 bits, respectively, for the parameter sets ML-DSA-65 and ML-DSA-87. 
```
