### ISSUE TITLE
Enable -Wconversion?

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#63]
The Windows `/W4` flag complains about conversions from larger to smaller integer types. (See also #61 ) The `gcc` and `clang` compilers also support `-Wconversion`, to report similar errors.

I'd suggest turning on this warning flag to shorten the development cycle of people programming stuff on Windows, but somehow Windows doesn't have problems with the Kyber768 code, while GCC and Clang do [find a lot of problems](https://gist.github.com/95718b4e893a5d6f963861a220edbb5b).

Do we want to include `-Wconversion`?

**Comment by dstebila** [comment]
Makes sense.

**Comment by cryptojedi** [comment]
Thom Wiggers <notifications@github.com> wrote:
> The Windows `/W4` flag complains about conversions from larger to smaller integer types. (See also #61 ) The `gcc` and `clang` compilers also support `-Wconversion`, to report similar errors.
> 
> I'd suggest turning on this warning flag to shorten the development cycle of people programming stuff on Windows, but somehow Windows doesn't have problems with the Kyber768 code, while GCC and Clang do [find a lot of problems](https://gist.github.com/95718b4e893a5d6f963861a220edbb5b).
> 
> Do we want to include `-Wconversion`?

It depends a bit on what it does. Apparently, it was subject of
controversy before, see
https://www.reddit.com/r/C_Programming/comments/3dtlsy/gcc_511_makes_wconversion_worthless_again/

Looking at that example code adding two chars there, I agree with the
statement that you really wouldn't want warnings.

**Comment by thomwiggers** [comment]
I do think it's weird that Windows somehow doesn't complain about the kyber code while `-Wconversion` seems to complain exactly similar complains that I needed to fix in #61. I'd like compilers to complain about similar things, so that people don't need to go through appveyor dozens of times, but then `-Wconversion` should do sensible things...

**Comment by thomwiggers** [comment]
`-Wconversion` indeed complains about too many things, we'll leave it off.
