### ISSUE TITLE
Build and test in 32-bit mode

### ISSUE THREAD

**Issue by thomwiggers** [PQClean/PQClean#7]
It's probably fine to do this on Travis' `x86_64` machines: I don't think 32-bit compiled executables are allowed to use the `_64` part of `x86_64`. We may need to complicate the setup of the build environment to add 32-bit libraries: do this through the `matrix`.

**Comment by joostrijneveld** [comment]
Implemented per https://github.com/PQClean/PQClean/commit/1f9da4b7113561a9241c11197350b4fd734ddcd1
