### ISSUE TITLE
Add lengths to META.yml

### ISSUE THREAD

**Issue by dstebila** [PQClean/PQClean#84]
META.yml files currently include length-public-key and length-ciphertext.  They should also include length-secret-key and length-shared-secret (for KEMs).  Similarly for signatures.

**Comment by dstebila** [comment]
Fixed by cc6516606301bd726d691da96412694a97e55b70.

**Comment by cryptojedi** [comment]
The size of the secret key can be different for different implementations; once we allow multiple implementations for one scheme, we need to revisit this one.

**Comment by joostrijneveld** [comment]
Good point. Is there anything against moving `length-secret-key:` to be a child of each entry in `implementations:`?

**Comment by dstebila** [comment]
> Good point. Is there anything against moving `length-secret-key:` to be a child of each entry in `implementations:`?

Seems fine.
