### ISSUE TITLE
Document rationale for inclusion criteria

### ISSUE THREAD

**Issue by joostrijneveld** [PQClean/PQClean#97]
The motivation for some of the checks we perform is perhaps obvious, but that's not the case for all. I often find myself asking or trying to remember what the exact motivation was. Some are documented in issues or pull requests, but many also surfaced during offline discussion.

Also as a justification towards potentially frustrated contributors, we should write up a small motivation for each of the checks we perform. Perhaps a separate markdown file?

**Comment by cryptojedi** [comment]
Joost Rijneveld <notifications@github.com> wrote:
> The motivation for some of the checks we perform is perhaps obvious,
> but that's not the case for all. I often find myself asking or trying
> to remember what the exact motivation was. Some are documented in
> issues or pull requests, but many also surfaced during offline
> discussion.
> 
> Also as a justification towards potentially frustrated contributors,
> we should write up a small motivation for each of the checks we
> perform. Perhaps a separate markdown file?

Sounds like a good idea, yes. How about something like MOTIVATION.md or
CLEANDEF.md? In any case, it should be referenced from README

**Comment by dstebila** [comment]
I added https://github.com/PQClean/PQClean/wiki/Test-framework which contains an explanation of every test in the test framework. If you think this is sufficient, we can close this issue. Otherwise, I suggest one of you write a wiki page explaining further.

**Comment by joostrijneveld** [comment]
Nice! I'm still missing the 'rationale' part, though. E.g:

> *dynamic_memory:* Checks that each implementation does not use dynamic memory functions (malloc, free, realloc, calloc).

While that's useful, I assume that's what most people would get from the name of the test alone. What's less obvious is _why_ we care (i.e., because it can fail? Because it's typically not available on embedded devices? Because it costs a bunch of cycles?)

**Comment by dstebila** [comment]
Okay. I've added a rationale sentence to all of the C checks.
